document.addEventListener("DOMContentLoaded", function () {
  const cropData = [
    {
      slno: "1",
      name: "Rice",
      nitrogen: "90",
      phosphorus: "42",
      potassium: "43",
      temperature: "20.87",
      humidity: "82.00",
      soilmoisture: "29.44",
      sunlight: "8.67",
      rainfall: "202.93",
      state : "Andaman and Nicobar",
      Fertiliser: "Urea",
    },
    {
      slno:"2",
      name: "Rice",
      nitrogen: "85",
      phosphorus: "58",
      potassium: "41",
      temperature: "21.77",
      humidity: "80.31",
      soilmoisture: "29.44",
      sunlight: "5.75",
      rainfall: "226.65",
      state : "Andaman and Nicobar",
      Fertiliser: "DAP",
    },
    {
      slno:"3",
      name: "Rice",
      nitrogen: "89",
      phosphorus: "54",
      potassium: "38",
      temperature: "24.51",
      humidity: "83.53",
      soilmoisture: "26.64",
      sunlight: "11.60",
      rainfall: "230.44",
      state : "Gujarat",
      Fertiliser: "28-28"
    },
    {
      slno: "4",
      name: "Rice",
      nitrogen: "60",
      phosphorus: "48",
      potassium: "39",
      temperature: "24.28",
      humidity: "80.30",
      soilmoisture: "23.34",
      sunlight: "10.16",
      rainfall: "231.08",
      state : "Andhra Pradesh",
      Fertiliser: "17-17-17"
    },
    {
      slno: "5",
      name: "Rice",
      nitrogen: "59",
      phosphorus: "67",
      potassium: "41",
      temperature: "21.94",
      humidity: "80.97",
      soilmoisture: "13.92",
      sunlight: "8.40",
      rainfall: "213.35",
      state : "Assam",
      Fertiliser: "DAP"
    },
    {
      slno: "6",
      name: "Maize",
      nitrogen: "71",
      phosphorus: "54",
      potassium: "16",
      temperature: "22.61",
      humidity: "63.69",
      soilmoisture: "28.15",
      sunlight: "10.45",
      rainfall: "87.75",
      state: "Gujarat",
      Fertiliser: "20-20",
    },
    {
      slno: "7",
      name: "Maize",
      nitrogen: "80",
      phosphorus: "43",
      potassium: "16",
      temperature: "23.55",
      humidity: "71.59",
      soilmoisture: "15.37",
      sunlight: "6.33",
      rainfall: "66.71",
      state: "Gujarat",
      Fertiliser: "17-17-17",
    },
    {
      slno: "8",
      name: "Maize",
      nitrogen: "61",
      phosphorus: "38",
      potassium: "20",
      temperature: "18.47",
      humidity: "62.69",
      soilmoisture: "26.64",
      sunlight: "6.94",
      rainfall: "65.43",
      state: "Gujarat",
      Fertiliser: "Urea",
    },
    {
      slno: "9",
      name: "Maize",
      nitrogen: "67",
      phosphorus: "60",
      potassium: "25",
      temperature: "24.92",
      humidity: "66.78",
      soilmoisture: "18.81",
      sunlight: "7.35",
      rainfall: "109.21",
      state: "Gujarat",
      Fertiliser: "Urea",
    },
    {
      slno: "10",
      name: "Maize",
      nitrogen: "90",
      phosphorus: "57",
      potassium: "24",
      temperature: "18.92",
      humidity: "72.80",
      soilmoisture: "14.20",
      sunlight: "7.51",
      rainfall: "82.34",
      state: "Gujarat",
      Fertiliser: "14-35-14", 
    },
    {
      slno: "11",
      name: "Maize",
      nitrogen: "67",
      phosphorus: "35",
      potassium: "22",
      temperature: "23.30",
      humidity: "63.24",
      soilmoisture: "14.64",
      sunlight: "5.67",
      rainfall: "108.76",
      state: "Gujarat",
      Fertiliser: "28-28", 
    },
    {
      slno: "12",
      name: "Mango",
      nitrogen: "2",
      phosphorus: "40",
      potassium: "27",
      temperature: "29.73",
      humidity: "47.54",
      soilmoisture: "15.15",
      sunlight: "5.21",
      rainfall: "90.09",
      state: "Punjab",
      Fertiliser: "20-20", 
    },
    {
      slno: "13",
      name: "Mango",
      nitrogen: "25",
      phosphorus: "22",
      potassium: "25",
      temperature: "33.56",
      humidity: "45.53",
      soilmoisture: "18.97",
      sunlight: "5.85",
      rainfall: "95.70",
      state: "Punjab",
      Fertiliser: "DAP", 
    },
    {
      slno: "14",
      name: "Mango",
      nitrogen: "11",
      phosphorus: "36",
      potassium: "33",
      temperature: "35.99",
      humidity: "52.22",
      soilmoisture: "12.97",
      sunlight: "8.32",
      rainfall: "95.37",
      state: "Punjab",
      Fertiliser: "DAP", 
    },
    {
      slno: "15",
      name: "Mango",
      nitrogen: "30",
      phosphorus: "28",
      potassium: "30",
      temperature: "31.86",
      humidity: "52.19",
      soilmoisture: "13.17",
      sunlight: "6.68",
      rainfall: "98.46",
      state: "Punjab",
      Fertiliser: "17-17-17", 
    },
    {
      slno: "16",
      name: "Banana",
      nitrogen: "105",
      phosphorus: "95",
      potassium: "50",
      temperature: "27.33",
      humidity: "83.67",
      soilmoisture: "23.03",
      sunlight: "10.56",
      rainfall: "101.04",
      state: "Odisha",
      Fertiliser: "20-20", 
    },
    {
      slno: "17",
      name: "Banana",
      nitrogen: "91",
      phosphorus: "94",
      potassium: "46",
      temperature: "29.36",
      humidity: "76.24",
      soilmoisture: "12.92",
      sunlight: "5.04",
      rainfall: "92.82",
      state: "Odisha",
      Fertiliser: "Urea", 
    },
    {
      slno: "18",
      name: "Banana",
      nitrogen: "119",
      phosphorus: "72",
      potassium: "55",
      temperature: "25.99",
      humidity: "83.33",
      soilmoisture: "24.81",
      sunlight: "10.47",
      rainfall: "112.07",
      state: "Pondicherry",
      Fertiliser: "14-35-14", 
    },
    {
      slno: "19",
      name: "Banana",
      nitrogen: "101",
      phosphorus: "70",
      potassium: "48",
      temperature: "25.36",
      humidity: "75.03",
      soilmoisture: "15.53",
      sunlight: "9.19",
      rainfall: "116.55",
      state: "Pondicherry",
      Fertiliser: "28-28", 
    },
    {
      slno: "20",
      name: "Banana",
      nitrogen: "82",
      phosphorus: "78",
      potassium: "46",
      temperature: "25.05",
      humidity: "84.97",
      soilmoisture: "25.33",
      sunlight: "11.71",
      rainfall: "110.44",
      state: "Punjab",
      Fertiliser: "DAP", 
    },
    {
      slno: "21",
      name: "Banana",
      nitrogen: "106",
      phosphorus: "70",
      potassium: "55",
      temperature: "25.86",
      humidity: "78.52",
      soilmoisture: "22.32",
      sunlight: "11.57",
      rainfall: "116.30",
      state: "Punjab",
      Fertiliser: "17-17-17", 
    },
    {
      slno: "22",
      name: "Papaya",
      nitrogen: "32",
      phosphorus: "68",
      potassium: "52",
      temperature: "32.68",
      humidity: "92.61",
      soilmoisture: "10.21",
      sunlight: "6.52",
      rainfall: "248.85",
      state: "Uttar Pradesh",
      Fertiliser: "20-20", 
    },
  ];

  const tableBody = document
    .getElementById("crop-table")
    .getElementsByTagName("tbody")[0];
  cropData.forEach((crop) => {
    let row = tableBody.insertRow();
    Object.values(crop).forEach((text) => {
      let cell = row.insertCell();
      cell.appendChild(document.createTextNode(text));
    });
  });
});
